name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create environment file
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "RBD_GUILD_ID=${{ secrets.RBD_GUILD_ID }}" >> .env
          echo "RBD_CHANNEL_ID=${{ secrets.RBD_CHANNEL_ID }}" >> .env

      - name: Build and save Docker image
        run: |
          docker build -t zent-bot:${{ github.ref_name }} -t zent-bot:latest .
          docker save zent-bot:${{ github.ref_name }} | gzip > zent-bot.tar.gz

      - name: Transfer Docker image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "zent-bot.tar.gz,docker-compose.yml,.env"
          target: "/tmp/zent-bot/"

      - name: Copy and deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /tmp/zent-bot

            docker load < zent-bot.tar.gz

            docker compose -f docker-compose.yml up -d

            rm zent-bot.tar.gz
            docker image prune -f
